# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "bio-dbla-classifier"
  s.version = "0.7.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["George Githinji"]
  s.date = "2013-09-11"
  s.description = "Methods to classify and manipulate PfEMP1 DBL-alpha sequence tags"
  s.email = "georgkam@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bio-dbla-classifier.gemspec",
    "lib/bio-dbla-classifier.rb",
    "lib/bio/sequence/aa/aa.rb",
    "lib/bio/sequence/na/na.rb",
    "spec/aa_spec.rb",
    "spec/bio-dbla-classifier_spec.rb",
    "spec/na_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/georgeG/bioruby-dbla-classifier"
  s.licenses = ["Ruby"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "A tool to classify and manipulate PfEMP1 DBL-alpha sequence tags"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bio>, [">= 1.4.3"])
      s.add_development_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.22"])
      s.add_development_dependency(%q<jeweler>, [">= 1.6.4"])
      s.add_development_dependency(%q<rake>, [">= 0.9.2.2"])
    else
      s.add_dependency(%q<bio>, [">= 1.4.3"])
      s.add_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_dependency(%q<bundler>, [">= 1.0.22"])
      s.add_dependency(%q<jeweler>, [">= 1.6.4"])
      s.add_dependency(%q<rake>, [">= 0.9.2.2"])
    end
  else
    s.add_dependency(%q<bio>, [">= 1.4.3"])
    s.add_dependency(%q<rspec>, [">= 2.8.0"])
    s.add_dependency(%q<bundler>, [">= 1.0.22"])
    s.add_dependency(%q<jeweler>, [">= 1.6.4"])
    s.add_dependency(%q<rake>, [">= 0.9.2.2"])
  end
end

